#!/usr/bin/env bash
# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
#
# Release-driven schema versioning. Reads the OBI release version from
# versions.yaml and, for that version:
#   1. cuts site/schemas/obi/<version> (previous published file plus a new,
#      empty <version>: entry on top — a cumulative superset, like semconv),
#   2. bumps the emitted schema_url constant (OBISchemaURL) and the weaver
#      registry manifest schema_url to <version>.
#
# The new version's transformations are derived from the renames declared in the
# registry (`deprecated: {reason: renamed, renamed_to: ...}`), skipping any pair
# already recorded in an earlier version. Renames that are not declared that way
# still have to be added by hand (see devdocs/telemetry-schema.md). Files are
# immutable once published: never edit a released version.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OCI_BIN="${OCI_BIN:-docker}"
WEAVER_IMAGE="${WEAVER_IMAGE:-$(awk '$4=="weaver" {print $2}' "$ROOT/dependencies.Dockerfile")}"
BASE_URL="https://open-telemetry.github.io/opentelemetry-ebpf-instrumentation/schemas/obi"
SCHEMA_DIR="$ROOT/site/schemas/obi"
REGISTRY="$ROOT/schemas/obi"
SCHEMA_VERSION_FILE="$ROOT/pkg/export/attributes/names/schema_version.go"
MANIFEST="$ROOT/schemas/obi/manifest.yaml"

fail() { echo "generate-schema-next: $1" >&2; exit 1; }

version="$(awk '/^  obi:/{o=1} o&&/version:/{v=$2; sub(/^v/,"",v); print v; exit}' "$ROOT/versions.yaml")"
[ -n "$version" ] || fail "could not read the obi version from versions.yaml"
echo "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || fail "versions.yaml obi version '$version' is not MAJOR.MINOR.PATCH"

new_file="$SCHEMA_DIR/$version"
if [ -f "$new_file" ]; then
	echo "generate-schema-next: schema file for $version already exists — leaving it (preserving any hand-added transformations)"
else
	prev="$(printf '%s\n' "$SCHEMA_DIR"/* | sed 's#.*/##' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1 || true)"
	[ -n "$prev" ] || fail "no previous schema file under $SCHEMA_DIR to base $version on"
	grep -Eq '^versions:[[:space:]]*$' "$SCHEMA_DIR/$prev" || fail "previous file $prev has no 'versions:' block"
	# Renames already recorded in earlier versions must not repeat in the new
	# block; collect them as `old: new` pairs from the previous file.
	known="$(grep -E '^ {12,14}[^ ].*: ' "$SCHEMA_DIR/$prev" | sed 's/^ *//' || true)"

	resolved=$(mktemp)
	"$OCI_BIN" run --rm -v "$REGISTRY:/obi-registry:ro,z" -w /obi-registry \
		"$WEAVER_IMAGE" registry resolve --registry /obi-registry \
		--include-unreferenced --format json > "$resolved" 2>/dev/null || true

	changes=""
	if jq -e '.groups | length > 0' "$resolved" >/dev/null 2>&1; then
		changes="$(jq -r --arg known "$known" -f "$ROOT/scripts/schema-renames.jq" "$resolved")"
	else
		echo "generate-schema-next: could not resolve the registry; emitting no transformations" >&2
	fi
	rm -f "$resolved"

	{
		echo "file_format: 1.1.0"
		echo "schema_url: $BASE_URL/$version"
		echo "versions:"
		echo "  $version:"
		[ -n "$changes" ] && printf '%s\n' "$changes"
		awk 'f{print} /^versions:[[:space:]]*$/{f=1}' "$SCHEMA_DIR/$prev"
	} > "$new_file"
	if [ -n "$changes" ]; then
		echo "generate-schema-next: created site/schemas/obi/$version with the renames declared in the registry"
	else
		echo "generate-schema-next: created site/schemas/obi/$version with no transformations"
	fi
fi

# Regenerate the emitted URL constant and bump the registry manifest to <version>.
cat > "$SCHEMA_VERSION_FILE" <<EOF
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by scripts/generate-schema-next.sh; DO NOT EDIT.

package attr

var OBISchemaURL = "$BASE_URL/$version"
EOF
perl -i -pe "s#\\Q$BASE_URL/\\E[0-9]+\\.[0-9]+\\.[0-9]+#$BASE_URL/$version#g" "$MANIFEST"
echo "generate-schema-next: OBISchemaURL and manifest schema_url set to $version"
