name: Pull request checks

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions:
  contents: read

jobs:
  test:
    permissions:
      # Required for codecov
      checks: write
      pull-requests: write
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.25' ]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go }}
          cache: 'false'
      - name: Run verification and unit tests
        run: make docker-generate verify cov-exclude-generated
      - name: Report coverage
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./testoutput/cover.txt
          flags: unittests
